routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', 'HomeController@index');
Route::get('/register', 'AuthController@index')->name('register');
Route::post('/welcome', 'AuthController@store')->name('welcome');

Route::get('/', 'DashboardController@index');
Route::get('/table', 'DashboardController@table')->name('table');
Route::get('/data-tables', 'DashboardController@dataTable')->name('dataTable');

Route::resource('casts', 'CastController');

Route::get('/{any}', 'HomeController@index'); // Jika url tidak benar

app/Models/Cast.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    protected $guarded = [];
}

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    //
}

app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    //
}

app/Models/Kritik.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Kritik extends Model
{
    //
}

app/Models/Peran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Peran extends Model
{
    //
}

app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AuthController extends Controller
{
    public function index()
    {
        return view('register');
    }

    public function store(Request $request)
    {
        $name = $request->fname . ' ' . $request->lname;
        $data = $request->except('fname', 'lname');
        $data['name'] = $name;
        // dd($data);
        return view('home', compact('data'));
    }
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cast;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CastController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = DB::table('casts')->get();
        $data = Cast::get();
        return view('dashboard.casts.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.casts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // DB::table('casts')->insert([
        //     'nama' => $request->nama,
        //     'umur' => $request->umur,
        //     'bio' => $request->bio,
        //     'created_at' => Carbon::now()
        // ]);
        Cast::create($request->except('updated_at'));
        return redirect()->route('casts.index')->with('success', 'Cast data created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $data = DB::table('casts')->where('id', $id)->first();
        $data = Cast::findOrFail($id);
        return view('dashboard.casts.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $data = DB::table('casts')->where('id', $id)->first();
        $data = Cast::findOrFail($id);
        return view('dashboard.casts.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // DB::table('casts')->where('id', $id)->update([
        //     'nama' => $request->nama,
        //     'umur' => $request->umur,
        //     'bio' => $request->bio,
        //     'updated_at' => Carbon::now()
        // ]);
        Cast::findOrFail($id)->update($request->except('created_at'));
        return redirect()->route('casts.index')->with('success', 'Cast data updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // DB::table('casts')->where('id', $id)->delete();
        Cast::findOrFail($id)->delete();
        return redirect()->route('casts.index')->with('success', 'Cast data deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('dashboard.index');
    }

    public function table()
    {
        return view('dashboard.table');
    }

    public function dataTable()
    {
        return view('dashboard.datatable');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('welcome');
    }
}

resources/views/dashboard/casts/create.blade.php
@extends('layouts.master')
@section('title', 'Create Cast')

@section('content')
<form action="{{ route('casts.store') }}" method="POST">
    @csrf
    <div class="form-group">
        <label for="nama">Nama</label>
        <input type="text" class="form-control" name="nama" placeholder="Masukan nama">
    </div>
    <div class="form-group">
        <label for="umur">Umur</label>
        <input type="number" class="form-control" name="umur" placeholder="Masukan umur">
    </div>
    <div class="form-group">
        <label for="bio">Bio</label>
        <textarea class="form-control" name="bio" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

resources/views/dashboard/casts/edit.blade.php
@extends('layouts.master')
@section('title', 'Edit Cast')

@section('content')
@extends('layouts.master')
@section('title', 'Create Cast')

@section('content')
<form action="{{ route('casts.update', $data->id) }}" method="POST">
    @method('PUT')
    @csrf
    <input type="hidden" name="id" value="{{ $data->id }}"> <br />

    <div class="form-group">
        <label for="nama">Nama</label>
        <input type="text" class="form-control" value="{{ $data->nama }}" name="nama" placeholder="Masukan nama">
    </div>
    <div class="form-group">
        <label for="umur">Umur</label>
        <input type="number" class="form-control" value="{{ $data->umur }}" name="umur" placeholder="Masukan umur">
    </div>
    <div class="form-group">
        <label for="bio">Bio</label>
        <textarea class="form-control" value="{{ $data->bio }}" name="bio" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@endsection

@endsection

resources/views/dashboard/casts/index.blade.php
@extends('layouts.master')
@section('title', 'Cast')

@section('button')
<a href="{{ route('casts.create') }}" class="btn-primary btn-sm">Create Cast</a>
@endsection

@section('content')
@if ($message = Session::get('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>
        <p>{{ $message }}</p>
    </strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif
<div class="row">
    @foreach ($data as $cast)
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12 d-flex align-items-stretch flex-column">
        <div class="card bg-light d-flex flex-fill">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-8">
                                <h2 class="lead"><b>{{ $cast->id }}. {{ $cast->nama }}</b></h2>
                            </div>
                            <div class="col-4">
                                <h6 class="text-muted">{{ $cast->umur }} Tahun</h6>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <p class="text-muted text-sm">
                            <b>Bio: </b> {{ $cast->bio }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="text-right">
                    <form action="{{ route('casts.destroy', $cast->id) }}" method="POST">
                        <a href="{{ route('casts.show', $cast->id) }}" class="btn btn-sm btn-primary">
                            <i class="fas fa-user"></i> View
                        </a>
                        <a href="{{ route('casts.edit', $cast->id) }}" class="btn btn-sm btn-info">
                            <i class="fas fa-pencil-alt"></i> Edit
                        </a>

                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i>Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endsection

resources/views/dashboard/casts/show.blade.php
@extends('layouts.master')
@section('title', 'Show')
@section('content')
<div class="card">
    <div class="card-header">
        {{ $data->nama }} - {{ $data->umur }} tahun
    </div>
    <div class="card-body">
        <blockquote class="blockquote mb-0">
            <p>{{ $data->bio }}</p>
            <a href="{{ route('casts.index') }}">
                <i class="fas fa-angle-double-left"></i> Back
            </a>
        </blockquote>
    </div>
</div>
@endsection

resources/views/dashboard/index.blade.php
@extends('layouts.master')
@section('title', 'Dashboard')

@section('content')
<h1>Jabar Coding Camp - Laravel</h1>
<h3>Tugas 13 - Memasangkan Template dengan Laravel Blade</h>
    @endsection

resources/views/dashboard/table.blade.php
@extends('layouts.master')
@section('title', 'Table')

@section('content')
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 10px">#</th>
            <th>Task</th>
            <th>Progress</th>
            <th style="width: 40px">Label</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1.</td>
            <td>Update software</td>
            <td>
                <div class="progress progress-xs">
                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                </div>
            </td>
            <td><span class="badge bg-danger">55%</span></td>
        </tr>
        <tr>
            <td>2.</td>
            <td>Clean database</td>
            <td>
                <div class="progress progress-xs">
                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                </div>
            </td>
            <td><span class="badge bg-warning">70%</span></td>
        </tr>
        <tr>
            <td>3.</td>
            <td>Cron job running</td>
            <td>
                <div class="progress progress-xs progress-striped active">
                    <div class="progress-bar bg-primary" style="width: 30%"></div>
                </div>
            </td>
            <td><span class="badge bg-primary">30%</span></td>
        </tr>
        <tr>
            <td>4.</td>
            <td>Fix and squish bugs</td>
            <td>
                <div class="progress progress-xs progress-striped active">
                    <div class="progress-bar bg-success" style="width: 90%"></div>
                </div>
            </td>
            <td><span class="badge bg-success">90%</span></td>
        </tr>
    </tbody>
</table>
@endsection

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">

    <!-- Styles -->
    <style>
        html,
        body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            /* margin: 0; */
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links>a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>

<body>
    <h1>SELAMAT DATANG {{ $data['name'] ? $data['name'] : '' }}!</h1>
    <h2>Terima kasih telah bergabung di SanberBook. Social Media kita bersama.</h2>

    <p>Nama : {{ $data['name'] ? $data['name'] : '' }}</p>
    <p>Gender : {{ $data['gender'] ? $data['gender'] : '' }}</p>
    <p>Nationality : {{ $data['nationality'] ? $data['nationality'] : '' }}</p>
    <p>
        Language Spoken :
        @foreach ($data['language'] as $item)
        <ul>
            <li>{{ $item }}</li>
        </ul>
        @endforeach
    </p>
    <p>Bio : {{ $data['bio'] ? $data['bio'] : '' }}</p>
</body>

</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>

    @include('layouts.partials.style')
</head>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        @include('layouts.partials.navbar')

        @include('layouts.partials.sidebar')

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>@yield('title')</h1>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">@yield('title')</h3> &nbsp;
                        @yield('button')

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        @yield('content')
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        @include('layouts.partials.footer')

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    @include('layouts.partials.script')
</body>

</html>

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
</footer>

resources/views/layouts/partials/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Home</a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/layouts/partials/script.blade.php
<!-- jQuery -->
<script src="{{ asset('template/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('template/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('template/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('template/dist/js/demo.js') }}"></script>
@stack('script')

resources/views/layouts/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ asset('template/index3.html') }}" class="brand-link">
        <img src="{{ asset('template/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('template/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2"
                    alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="/" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            Tables
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('table') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Table</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('dataTable') }}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>DataTable</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{ route('casts.index') }}" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Casts
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/partials/style.blade.php
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('template/plugins/fontawesome-free/css/all.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('template/dist/css/adminlte.min.css') }}">
@stack('style')

resources/views/register.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">

    <!-- Styles -->
    <style>
        html,
        body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            /* margin: 0; */
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links>a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 13px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>

<body>
    <h1>Buat Account Baru!</h1>
    <h3>Sign Up Form</h3>
    <form method="POST" action="{{ route('welcome') }}" id="form-pendaftaran">
        @csrf
        <p>First Name: </p>
        <input type="text" id="fname" name="fname">

        <p>Last Name: </p>
        <input type="text" id="lname" name="lname">

        <p>Gender:</p>
        <input type="radio" id="gender" name="gender" value="Male" checked>
        <label for="male">Male</label><br>

        <input type="radio" id="gender" name="gender" value="Female">
        <label for="female">Female</label><br>

        <input type="radio" id="gender" name="gender" value="Other">
        <label for="other">Other</label><br>

        <p>Nationality: </p>
        <select id="nationality" name="nationality">
            <option value="Indonesian">Indonesian</option>
            <option value="Singaporean">Singaporean</option>
            <option value="Malaysian">Malaysian</option>
            <option value="Australian">Australian</option>
        </select>

        <p>Language Spoken: </p>
        <input type="checkbox" id="language1" name="language[]" value="Bahasa Indonesia" checked>
        <label for="language1"> Bahasa Indonesia</label><br>
        <input type="checkbox" id="language2" name="language[]" value="English">
        <label for="language2"> English</label><br>
        <input type="checkbox" id="language3" name="language[]" value="Other">
        <label for="language3"> Other</label>

        <p>Bio: </p>
        <textarea name="bio" id="bio" cols="30" rows="10"></textarea><br>

        <input type="submit" form="form-pendaftaran" value="Submit">
    </form>
</body>

</html>